# This is a basic workflow to help you get started with Actions

name: Input data validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Run Nextflow unittests using nf-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: List test data
        run: |
          ls example_datasets/example_consensus_reads/  
          ls example_datasets/example_native_reads/

      # - name: Obtain seqkit stats
      #   run: seqkit stats testing/data/fastq_pass/*

      # - name: Run simple pipeline in docker
      #   run: |
      #     nextflow -v
      #     nextflow run main.nf --read_folder testing/data/fastq_pass --output_folder ignore_results1 -profile docker

      - name: Setup nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_PASSWORD }}

      - name: Run nf-test
        run: nf-test test --profile docker --economy_mode
